// ==========================================
// ALIGNER CASES DATA
// ==========================================
// You can easily modify each card's data here.

export const alignerCases: Record<string, any[]> = {
  "Overview": [
    {
      id: "aligner-Overview-1",
      patientInfo: "Female patient, 20 years old",
      duration: "12 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://i.postimg.cc/qM8TppKn/IMG-9919.jpg",
      afterImg: "https://i.postimg.cc/kMz4BYzy/IMG-2729.jpg",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-0-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-0-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-0-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-0-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-0-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-0-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-0-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-0-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-0-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-0-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-0-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-0-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-2",
      patientInfo: "Male patient, 26 years old",
      duration: "14 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://i.postimg.cc/6qk1D4zW/IMG-9922.jpg",
      afterImg: "https://i.postimg.cc/5tmdLgg1/IMG-2721-(1).jpg",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-1-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-1-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-1-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-1-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-1-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-1-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-1-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-1-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-1-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-1-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-1-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-1-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-3",
      patientInfo: "Female patient, 22 years old",
      duration: "16 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://i.postimg.cc/bJb61wp9/IMG-0704.jpg",
      afterImg: "https://i.postimg.cc/PqDbRV91/IMG-1049.jpg",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-2-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-2-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-2-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-2-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-2-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-2-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-2-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-2-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-2-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-2-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-2-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-2-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-4",
      patientInfo: "Male patient, 28 years old",
      duration: "18 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-4/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-4/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-3-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-3-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-3-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-3-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-3-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-3-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-3-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-3-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-3-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-3-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-3-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-3-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-5",
      patientInfo: "Female patient, 24 years old",
      duration: "20 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-5/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-5/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-4-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-4-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-4-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-4-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-4-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-4-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-4-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-4-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-4-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-4-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-4-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-4-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-6",
      patientInfo: "Male patient, 30 years old",
      duration: "22 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-6/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-6/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-5-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-5-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-5-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-5-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-5-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-5-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-5-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-5-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-5-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-5-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-5-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-5-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-7",
      patientInfo: "Female patient, 26 years old",
      duration: "24 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-7/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-7/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-6-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-6-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-6-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-6-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-6-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-6-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-6-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-6-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-6-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-6-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-6-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-6-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-8",
      patientInfo: "Male patient, 32 years old",
      duration: "26 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-8/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-8/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-7-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-7-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-7-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-7-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-7-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-7-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-7-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-7-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-7-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-7-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-7-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-7-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-9",
      patientInfo: "Female patient, 28 years old",
      duration: "28 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-9/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-9/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-8-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-8-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-8-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-8-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-8-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-8-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-8-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-8-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-8-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-8-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-8-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-8-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-10",
      patientInfo: "Male patient, 34 years old",
      duration: "30 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-10/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-10/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-9-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-9-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-9-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-9-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-9-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-9-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-9-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-9-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-9-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-9-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-9-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-9-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-11",
      patientInfo: "Female patient, 30 years old",
      duration: "32 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-11/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-11/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-10-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-10-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-10-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-10-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-10-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-10-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-10-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-10-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-10-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-10-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-10-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-10-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-12",
      patientInfo: "Male patient, 36 years old",
      duration: "34 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-12/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-12/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-11-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-11-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-11-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-11-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-11-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-11-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-11-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-11-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-11-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-11-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-11-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-11-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-13",
      patientInfo: "Female patient, 32 years old",
      duration: "36 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-13/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-13/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-12-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-12-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-12-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-12-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-12-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-12-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-12-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-12-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-12-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-12-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-12-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-12-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-14",
      patientInfo: "Male patient, 38 years old",
      duration: "38 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-14/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-14/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-13-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-13-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-13-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-13-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-13-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-13-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-13-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-13-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-13-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-13-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-13-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-13-11/1200/800" },
      ]
    },
    {
      id: "aligner-Overview-15",
      patientInfo: "Female patient, 34 years old",
      duration: "40 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Overview-15/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Overview-15/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Overview-14-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Overview-14-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Overview-14-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Overview-14-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Overview-14-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Overview-14-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Overview-14-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Overview-14-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Overview-14-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Overview-14-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Overview-14-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Overview-14-11/1200/800" },
      ]
    },
  ],
  "Mild": [
    {
      id: "aligner-Mild-1",
      patientInfo: "Female patient, 20 years old",
      duration: "12 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-1/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-1/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-0-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-0-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-0-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-0-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-0-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-0-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-0-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-0-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-0-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-0-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-0-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-0-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-2",
      patientInfo: "Male patient, 26 years old",
      duration: "14 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-2/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-2/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-1-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-1-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-1-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-1-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-1-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-1-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-1-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-1-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-1-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-1-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-1-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-1-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-3",
      patientInfo: "Female patient, 22 years old",
      duration: "16 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-3/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-3/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-2-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-2-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-2-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-2-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-2-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-2-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-2-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-2-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-2-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-2-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-2-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-2-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-4",
      patientInfo: "Male patient, 28 years old",
      duration: "18 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-4/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-4/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-3-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-3-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-3-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-3-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-3-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-3-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-3-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-3-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-3-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-3-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-3-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-3-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-5",
      patientInfo: "Female patient, 24 years old",
      duration: "20 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-5/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-5/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-4-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-4-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-4-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-4-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-4-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-4-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-4-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-4-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-4-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-4-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-4-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-4-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-6",
      patientInfo: "Male patient, 30 years old",
      duration: "22 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-6/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-6/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-5-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-5-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-5-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-5-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-5-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-5-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-5-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-5-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-5-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-5-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-5-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-5-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-7",
      patientInfo: "Female patient, 26 years old",
      duration: "24 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-7/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-7/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-6-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-6-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-6-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-6-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-6-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-6-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-6-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-6-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-6-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-6-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-6-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-6-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-8",
      patientInfo: "Male patient, 32 years old",
      duration: "26 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-8/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-8/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-7-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-7-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-7-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-7-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-7-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-7-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-7-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-7-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-7-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-7-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-7-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-7-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-9",
      patientInfo: "Female patient, 28 years old",
      duration: "28 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-9/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-9/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-8-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-8-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-8-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-8-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-8-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-8-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-8-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-8-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-8-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-8-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-8-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-8-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-10",
      patientInfo: "Male patient, 34 years old",
      duration: "30 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-10/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-10/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-9-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-9-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-9-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-9-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-9-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-9-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-9-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-9-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-9-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-9-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-9-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-9-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-11",
      patientInfo: "Female patient, 30 years old",
      duration: "32 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-11/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-11/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-10-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-10-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-10-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-10-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-10-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-10-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-10-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-10-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-10-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-10-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-10-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-10-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-12",
      patientInfo: "Male patient, 36 years old",
      duration: "34 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-12/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-12/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-11-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-11-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-11-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-11-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-11-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-11-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-11-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-11-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-11-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-11-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-11-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-11-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-13",
      patientInfo: "Female patient, 32 years old",
      duration: "36 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-13/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-13/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-12-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-12-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-12-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-12-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-12-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-12-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-12-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-12-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-12-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-12-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-12-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-12-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-14",
      patientInfo: "Male patient, 38 years old",
      duration: "38 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-14/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-14/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-13-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-13-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-13-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-13-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-13-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-13-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-13-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-13-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-13-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-13-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-13-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-13-11/1200/800" },
      ]
    },
    {
      id: "aligner-Mild-15",
      patientInfo: "Female patient, 34 years old",
      duration: "40 months",
      description: "Detailed description for this specific case of Mild. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Mild-15/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Mild-15/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Mild-14-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Mild-14-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Mild-14-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Mild-14-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Mild-14-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Mild-14-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Mild-14-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Mild-14-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Mild-14-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Mild-14-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Mild-14-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Mild-14-11/1200/800" },
      ]
    },
  ],
  "Complex": [
    {
      id: "aligner-Complex-1",
      patientInfo: "Female patient, 20 years old",
      duration: "12 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-1/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-1/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-0-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-0-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-0-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-0-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-0-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-0-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-0-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-0-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-0-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-0-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-0-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-0-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-2",
      patientInfo: "Male patient, 26 years old",
      duration: "14 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-2/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-2/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-1-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-1-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-1-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-1-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-1-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-1-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-1-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-1-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-1-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-1-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-1-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-1-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-3",
      patientInfo: "Female patient, 22 years old",
      duration: "16 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-3/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-3/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-2-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-2-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-2-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-2-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-2-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-2-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-2-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-2-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-2-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-2-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-2-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-2-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-4",
      patientInfo: "Male patient, 28 years old",
      duration: "18 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-4/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-4/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-3-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-3-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-3-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-3-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-3-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-3-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-3-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-3-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-3-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-3-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-3-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-3-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-5",
      patientInfo: "Female patient, 24 years old",
      duration: "20 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-5/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-5/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-4-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-4-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-4-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-4-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-4-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-4-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-4-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-4-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-4-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-4-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-4-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-4-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-6",
      patientInfo: "Male patient, 30 years old",
      duration: "22 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-6/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-6/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-5-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-5-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-5-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-5-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-5-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-5-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-5-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-5-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-5-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-5-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-5-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-5-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-7",
      patientInfo: "Female patient, 26 years old",
      duration: "24 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-7/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-7/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-6-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-6-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-6-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-6-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-6-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-6-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-6-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-6-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-6-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-6-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-6-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-6-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-8",
      patientInfo: "Male patient, 32 years old",
      duration: "26 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-8/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-8/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-7-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-7-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-7-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-7-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-7-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-7-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-7-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-7-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-7-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-7-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-7-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-7-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-9",
      patientInfo: "Female patient, 28 years old",
      duration: "28 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-9/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-9/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-8-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-8-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-8-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-8-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-8-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-8-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-8-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-8-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-8-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-8-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-8-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-8-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-10",
      patientInfo: "Male patient, 34 years old",
      duration: "30 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-10/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-10/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-9-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-9-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-9-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-9-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-9-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-9-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-9-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-9-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-9-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-9-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-9-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-9-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-11",
      patientInfo: "Female patient, 30 years old",
      duration: "32 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-11/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-11/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-10-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-10-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-10-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-10-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-10-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-10-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-10-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-10-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-10-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-10-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-10-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-10-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-12",
      patientInfo: "Male patient, 36 years old",
      duration: "34 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-12/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-12/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-11-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-11-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-11-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-11-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-11-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-11-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-11-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-11-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-11-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-11-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-11-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-11-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-13",
      patientInfo: "Female patient, 32 years old",
      duration: "36 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-13/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-13/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-12-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-12-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-12-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-12-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-12-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-12-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-12-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-12-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-12-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-12-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-12-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-12-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-14",
      patientInfo: "Male patient, 38 years old",
      duration: "38 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-14/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-14/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-13-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-13-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-13-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-13-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-13-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-13-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-13-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-13-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-13-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-13-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-13-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-13-11/1200/800" },
      ]
    },
    {
      id: "aligner-Complex-15",
      patientInfo: "Female patient, 34 years old",
      duration: "40 months",
      description: "Detailed description for this specific case of Complex. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-aligner-Complex-15/800/800",
      afterImg: "https://picsum.photos/seed/after-aligner-Complex-15/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-aligner-Complex-14-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-aligner-Complex-14-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-aligner-Complex-14-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-aligner-Complex-14-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-aligner-Complex-14-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-aligner-Complex-14-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-aligner-Complex-14-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-aligner-Complex-14-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-aligner-Complex-14-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-aligner-Complex-14-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-aligner-Complex-14-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-aligner-Complex-14-11/1200/800" },
      ]
    },
  ],
};
