// ==========================================
// BIMAXILLARY-PROTRUSION CASES DATA
// ==========================================
// You can easily modify each card's data here.

export const bimaxillaryProtrusionCases: Record<string, any[]> = {
  "Overview": [
    {
      id: "bimaxillary-protrusion-Overview-1",
      patientInfo: "Female patient, 20 years old",
      duration: "12 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://i.postimg.cc/jjpV9SBh/IMG-7760.jpg",
      afterImg: "https://i.postimg.cc/MHtFW6rK/IMG-7769.jpg",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://i.postimg.cc/wMh9Fmvf/IMG-7755.jpg" },
        { label: "Month 2", timeframe: "Month 2", img: "https://i.postimg.cc/tCNXxW89/IMG-7756.jpg" },
        { label: "Month 3", timeframe: "Month 3", img: "https://i.postimg.cc/mrzf8HpS/IMG-7757.jpg" },
        { label: "Month 4", timeframe: "Month 4", img: "https://i.postimg.cc/zDkMw7D6/IMG-7763.jpg" },
        { label: "Month 5", timeframe: "Month 5", img: "https://i.postimg.cc/rFFHf4KW/IMG-7765.jpg" },
        { label: "Month 6", timeframe: "Month 6", img: "https://i.postimg.cc/PfMcbyrf/IMG-7764.jpg" }
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-2",
      patientInfo: "Female patient, 26 years old",
      duration: "14 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://i.postimg.cc/W1VdR2cr/IMG-7753.jpg",
      afterImg: "https://i.postimg.cc/qRvBJR1R/IMG-7746.jpg",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://i.postimg.cc/v86Tc1Qt/IMG-7754.jpg" },
        { label: "Month 2", timeframe: "Month 2", img: "https://i.postimg.cc/G2fRbjB7/IMG-7752.jpg" },
        { label: "Month 3", timeframe: "Month 3", img: "https://i.postimg.cc/nLtCJn82/IMG-7741.jpg" },
        { label: "Month 8", timeframe: "Month 8", img: "https://i.postimg.cc/qqg7LRK8/IMG-7742.jpg" },
        { label: "Month 4", timeframe: "Month 4", img: "https://i.postimg.cc/qqYvZTX0/IMG-7743.jpg" },
        { label: "Month 5", timeframe: "Month 5", img: "https://i.postimg.cc/N0pYztQM/IMG-7750.jpg" },
        { label: "Month 6", timeframe: "Month 6", img: "https://i.postimg.cc/h43vGLFN/IMG-7744.jpg" },
        { label: "Month 7", timeframe: "Month 7", img: "https://i.postimg.cc/Pq4rnZz2/IMG-7745.jpg" },
        { label: "Month 9", timeframe: "Month 9", img: "https://i.postimg.cc/3wMDxgGr/IMG-1332.jpg" },
        { label: "Month 10", timeframe: "Month 10", img: "https://i.postimg.cc/jq8w7VNs/IMG-1333.jpg" },
        { label: "Month 11", timeframe: "Month 11", img: "https://i.postimg.cc/59PYCcz3/IMG-6003.jpg" },
        { label: "Final Result", timeframe: "Month 12", img: "https://i.postimg.cc/Kvw10nJH/IMG-6005.jpg" },
        { label: "Final Result", timeframe: "Month 12", img: "https://i.postimg.cc/bY6DtXbc/IMG-6004.jpg" },
        { label: "Final Result", timeframe: "Month 12", img: "https://i.postimg.cc/Rh3MtY5z/IMG-7747.jpg" },
        { label: "Final Result", timeframe: "Month 12", img: "https://i.postimg.cc/dQXQFJrC/IMG-7748.jpg" },
        
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-3",
      patientInfo: "Female patient, 22 years old",
      duration: "16 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-3/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-3/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-2-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-4",
      patientInfo: "Male patient, 28 years old",
      duration: "18 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-4/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-4/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-3-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-5",
      patientInfo: "Female patient, 24 years old",
      duration: "20 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-5/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-5/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-4-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-6",
      patientInfo: "Male patient, 30 years old",
      duration: "22 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-6/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-6/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-5-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-7",
      patientInfo: "Female patient, 26 years old",
      duration: "24 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-7/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-7/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-6-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-8",
      patientInfo: "Male patient, 32 years old",
      duration: "26 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-8/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-8/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-7-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-9",
      patientInfo: "Female patient, 28 years old",
      duration: "28 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-9/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-9/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-8-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-10",
      patientInfo: "Male patient, 34 years old",
      duration: "30 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-10/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-10/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-9-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-11",
      patientInfo: "Female patient, 30 years old",
      duration: "32 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-11/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-11/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-10-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-12",
      patientInfo: "Male patient, 36 years old",
      duration: "34 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-12/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-12/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-11-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-13",
      patientInfo: "Female patient, 32 years old",
      duration: "36 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-13/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-13/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-12-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-14",
      patientInfo: "Male patient, 38 years old",
      duration: "38 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-14/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-14/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-13-11/1200/800" },
      ]
    },
    {
      id: "bimaxillary-protrusion-Overview-15",
      patientInfo: "Female patient, 34 years old",
      duration: "40 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-bimaxillary-protrusion-Overview-15/800/800",
      afterImg: "https://picsum.photos/seed/after-bimaxillary-protrusion-Overview-15/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-bimaxillary-protrusion-Overview-14-11/1200/800" },
      ]
    },
  ],
};
