// ==========================================
// IMPACTED-TEETH CASES DATA
// ==========================================
// You can easily modify each card's data here.

export const impactedTeethCases: Record<string, any[]> = {
  "Overview": [
    {
      id: "impacted-teeth-Overview-1",
      patientInfo: "Female patient, 20 years old",
      duration: "12 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-1/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-1/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-0-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-2",
      patientInfo: "Male patient, 26 years old",
      duration: "14 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-2/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-2/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-1-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-3",
      patientInfo: "Female patient, 22 years old",
      duration: "16 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-3/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-3/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-2-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-4",
      patientInfo: "Male patient, 28 years old",
      duration: "18 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-4/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-4/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-3-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-5",
      patientInfo: "Female patient, 24 years old",
      duration: "20 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-5/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-5/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-4-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-6",
      patientInfo: "Male patient, 30 years old",
      duration: "22 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-6/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-6/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-5-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-7",
      patientInfo: "Female patient, 26 years old",
      duration: "24 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-7/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-7/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-6-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-8",
      patientInfo: "Male patient, 32 years old",
      duration: "26 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-8/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-8/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-7-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-9",
      patientInfo: "Female patient, 28 years old",
      duration: "28 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-9/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-9/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-8-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-10",
      patientInfo: "Male patient, 34 years old",
      duration: "30 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-10/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-10/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-9-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-11",
      patientInfo: "Female patient, 30 years old",
      duration: "32 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-11/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-11/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-10-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-12",
      patientInfo: "Male patient, 36 years old",
      duration: "34 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-12/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-12/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-11-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-13",
      patientInfo: "Female patient, 32 years old",
      duration: "36 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-13/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-13/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-12-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-14",
      patientInfo: "Male patient, 38 years old",
      duration: "38 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-14/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-14/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-13-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Overview-15",
      patientInfo: "Female patient, 34 years old",
      duration: "40 months",
      description: "Detailed description for this specific case of Overview. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Overview-15/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Overview-15/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Overview-14-11/1200/800" },
      ]
    },
  ],
  "Canines": [
    {
      id: "impacted-teeth-Canines-1",
      patientInfo: "Female patient, 20 years old",
      duration: "12 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-1/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-1/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-0-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-2",
      patientInfo: "Male patient, 26 years old",
      duration: "14 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-2/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-2/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-1-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-3",
      patientInfo: "Female patient, 22 years old",
      duration: "16 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-3/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-3/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-2-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-4",
      patientInfo: "Male patient, 28 years old",
      duration: "18 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-4/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-4/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-3-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-5",
      patientInfo: "Female patient, 24 years old",
      duration: "20 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-5/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-5/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-4-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-6",
      patientInfo: "Male patient, 30 years old",
      duration: "22 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-6/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-6/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-5-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-7",
      patientInfo: "Female patient, 26 years old",
      duration: "24 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-7/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-7/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-6-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-8",
      patientInfo: "Male patient, 32 years old",
      duration: "26 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-8/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-8/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-7-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-9",
      patientInfo: "Female patient, 28 years old",
      duration: "28 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-9/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-9/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-8-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-10",
      patientInfo: "Male patient, 34 years old",
      duration: "30 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-10/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-10/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-9-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-11",
      patientInfo: "Female patient, 30 years old",
      duration: "32 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-11/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-11/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-10-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-12",
      patientInfo: "Male patient, 36 years old",
      duration: "34 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-12/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-12/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-11-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-13",
      patientInfo: "Female patient, 32 years old",
      duration: "36 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-13/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-13/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-12-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-14",
      patientInfo: "Male patient, 38 years old",
      duration: "38 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-14/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-14/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-13-11/1200/800" },
      ]
    },
    {
      id: "impacted-teeth-Canines-15",
      patientInfo: "Female patient, 34 years old",
      duration: "40 months",
      description: "Detailed description for this specific case of Canines. Arch expansion and detailed bite coordination.",
      notes: "Patient reported high satisfaction and comfortable progression.",
      beforeImg: "https://picsum.photos/seed/before-impacted-teeth-Canines-15/800/800",
      afterImg: "https://picsum.photos/seed/after-impacted-teeth-Canines-15/800/800",
      progressImages: [
        { label: "Initial Record", timeframe: "Month 1", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-0/1200/800" },
        { label: "Month 2", timeframe: "Month 2", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-1/1200/800" },
        { label: "Month 3", timeframe: "Month 3", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-2/1200/800" },
        { label: "Month 4", timeframe: "Month 4", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-3/1200/800" },
        { label: "Month 5", timeframe: "Month 5", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-4/1200/800" },
        { label: "Month 6", timeframe: "Month 6", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-5/1200/800" },
        { label: "Month 7", timeframe: "Month 7", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-6/1200/800" },
        { label: "Month 8", timeframe: "Month 8", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-7/1200/800" },
        { label: "Month 9", timeframe: "Month 9", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-8/1200/800" },
        { label: "Month 10", timeframe: "Month 10", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-9/1200/800" },
        { label: "Month 11", timeframe: "Month 11", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-10/1200/800" },
        { label: "Final Result", timeframe: "Month 12", img: "https://picsum.photos/seed/prog-impacted-teeth-Canines-14-11/1200/800" },
      ]
    },
  ],
};
